#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
}

start() {
	ebegin "Starting nagzillad"
	start-stop-daemon --start --exec /usr/sbin/nagzillad
	eend $? "Failed to start nagzillad"
}

stop() {
	ebegin "Stopping ntpd"
	start-stop-daemon --stop \
		--exec /usr/sbin/nagzillad
	eend $? "Failed to stop nagzillad"
}
